import '../styles/globals.css'
import rubikFont from '@/constants/localFont'

export const metadata = {
	title: 'Frontend Quiz App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={`${rubikFont.variable} min-h-screen`}>
				{children}
			</body>
		</html>
	)
}
